### ISSUE TITLE
No face parsing onnx model found

### ISSUE THREAD

**Issue by ZTMIDGO** [ykk648/AI_power#2]
Can you provide a download link for the ONNX model of Face Parsing?

https://github.com/ykk648/AI_power/tree/main/face_lib/face_parsing

**Comment by ykk648** [comment]
as the README showed:  [BaiDuPan](https://pan.baidu.com/s/18MegZnMQn1oQR1jJPpWJxQ) pwd: ibgg

**Comment by ZTMIDGO** [comment]
thanks
