### ISSUE TITLE
Whether to consider incorporating EleGANt into the Ai_power

### ISSUE THREAD

**Issue by ZTMIDGO** [ykk648/AI_power#3]
Hello, are you considering incorporating this project ( https://github.com/Chenyu-Yang-2000/EleGANt ) into the Ai_power, which is better than PSGAN in makeup transfer?

**Comment by ZTMIDGO** [comment]
But my attempt to convert the project's model to onnx failed, here is my conversion code, but the conversion failed.

torch 2.0.1
torchvision 0.15.2

        device = 'cpu'
        c = torch.randn(1, 3, 256, 256, requires_grad=True).to(device)
        s = torch.randn(1, 3, 256, 256, requires_grad=True).to(device)

        mask_c = torch.randn(1, 2, 256, 256, requires_grad=True).to(device)
        mask_s = torch.randn(1, 2, 256, 256, requires_grad=True).to(device)

        diff_c = torch.randn(1, 136, 256, 256, requires_grad=True).to(device)
        diff_s = torch.randn(1, 136, 256, 256, requires_grad=True).to(device)

        lms_c = torch.randn(1, 68, 2, requires_grad=True).to(device)
        lms_s = torch.randn(1, 68, 2, requires_grad=True).to(device)

        input = ['c', 's', 'mask_c', 'mask_s', 'diff_c', 'diff_s', 'lms_c', 'lms_s']
        output = ['output']
        pytorch_export_contrib_ops.register()
        torch.onnx.export(self.solver.G, (c, s, mask_c, mask_s, diff_c, diff_s, lms_c, lms_s), 'model.onnx', verbose=True, 
        opset_version=15, input_names=input, output_names=output)

ERROR：torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::linalg_inv' to ONNX opset version 15 is not supported.

**Comment by ykk648** [comment]
torch.reverse算子onnx不支持
```
from torch.onnx import register_custom_op_symbolic
def my_inverse(g, self):
    return g.op("com.microsoft::Inverse", self)
register_custom_op_symbolic('aten::linalg_inv', my_inverse, 1)
```
然后会发现InstanceNorm2d onnx也报错

不建议转换，如果非要继续做就把模型结构拆分了，至少把TPSalign的部分剥出去

**Comment by ZTMIDGO** [comment]
> torch.reverse算子onnx不支持
> 
> ```
> from torch.onnx import register_custom_op_symbolic
> def my_inverse(g, self):
>     return g.op("com.microsoft::Inverse", self)
> register_custom_op_symbolic('aten::linalg_inv', my_inverse, 1)
> ```
> 
> 然后会发现InstanceNorm2d onnx也报错
> 
> 不建议转换，如果非要继续做就把模型结构拆分了，至少把TPSalign的部分剥出去

把TPSalign剥出去难度是不是好大？
我刚接触这方面不久，没有太多经验。

**Comment by ZTMIDGO** [comment]
可不可以通过修改 https://github.com/Chenyu-Yang-2000/EleGANt 项目的代码，把不友好的算子替换掉，然后重新训练模型再转换，这种做法是否可行？

**Comment by ykk648** [comment]
如果你能做到，那肯定可行，看你们的业务需求

如果是为了提速或者部署，拆分是最快的，我大概扫了一眼，TPStransformer的作用就是landmark对齐，没必要放在生成器里，具体没细看

**Comment by ZTMIDGO** [comment]
我查看了以下pytorch转onnx支持的算子 https://pytorch.org/docs/stable/onnx_supported_aten_ops.html ，只有400个不到，难怪转onnx老是碰墙

**Comment by ZTMIDGO** [comment]
想问一下是修改项目源码重新训练和拆分模型，两者哪个概率更大一点

**Comment by ZTMIDGO** [comment]
希望大佬有空可以去试一下分割结构，感谢指导

**Comment by ykk648** [comment]
拆分模型简单点，工作目前不涉及换妆，应该没时间做，不好意思

**Comment by ZTMIDGO** [comment]
你好，我成功把模型导出为onnx并成功推理产生的结果也是正确的(FP32)，但转换出的模型通过量化为UINT8后导致推理的结果不正确，能否帮我看看是什么原因？

导出代码
inference = Inference(config, args, args.load_path)
source_input, face, crop_face = inference.preprocess(imgA)
reference_input, _, _ = inference.preprocess(imgB)
source_input = inference.prepare_input(*source_input)
reference_input = inference.prepare_input(*reference_input)
image_A, mask_A, diff_A, lms_A, image_B, mask_B, diff_B, lms_B = [*source_input, *reference_input]
torch_model = inference.solver.G

inputs = image_A, image_B, mask_A, mask_B, diff_A, diff_B, lms_A, lms_B

def linalg_inv_settype(g, self):
    return g.op("com.microsoft::Inverse", self).setType(
        self.type().with_dtype(torch.float).with_sizes([None, 3, 3])
    )
torch.onnx.register_custom_op_symbolic("::linalg_inv", linalg_inv_settype, 9)

input = ['c', 's', 'mask_c', 'mask_s', 'diff_c', 'diff_s', 'lms_c', 'lms_s']
output = ['output']
torch.onnx.export(torch_model, inputs, "model_384.onnx", opset_version=16, input_names=input, output_names=output)

量化代码
`quantize_dynamic(model_input='D:/python/EleGan/model_384.onnx', model_output='D:/python/EleGan/model_quantize.onnx', weight_type=QuantType.QUInt8)`

**Comment by ykk648** [comment]
没有时间复现，建议使用静态量化，如果要定位量化精度损失，最好一层一层对比
