### ISSUE TITLE
hififace pretrained model

### ISSUE THREAD

**Issue by joe-zxh** [ykk648/AI_power#4]
Dear author, it seems that the baiduPan does not contain the hififace pretrained models, will you release them?

![image](https://github.com/ykk648/AI_power/assets/29706834/367c157e-a3bb-4a4f-a486-9af6a0466f6d)

**Comment by ykk648** [comment]
It's private model trained on private data and will not be released 🙂

**Comment by ykk648** [comment]
check https://github.com/GuijiAI/ReHiFace-S
